imports:
  - { resource: ./shared/application.dev.yaml }
  - { resource: ./modules/youtubeVideos/application.yaml}
  - { resource: ./modules/videoToConvertLater/application.yaml}
  - { resource: ./controllers/application.yaml }
