services:

  App.Rest.Controllers.HealthCheckGetController:
    class: ../../controllers/healthChecks/HealthCheckGetController
    arguments: [ ]

  App.Rest.Controllers.YoutubeVideosGetController:
    class: ../../controllers/youtubeVideos/YoutubeVideosGetController
    arguments: [ '@Platform.YoutubeVideos.YoutubeVideosSearcher' ]

  App.Rest.Controllers.VideosToConvertLaterPutController:
    class: ../../controllers/videosToConvertLater/VideosToConvertLaterPutController
    arguments: [ '' ]
